# Generated by Django 4.1.3 on 2023-04-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred_email',
            field=models.EmailField(default='lollol@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
