# Generated by Django 4.1.3 on 2023-04-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_academichistory_degree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
