# Generated by Django 4.1.3 on 2024-01-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_batch_number_alter_profile_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
