# Generated by Django 4.1.3 on 2024-02-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_options_user_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batch_number',
            field=models.CharField(max_length=10),
        ),
    ]
