# Generated by Django 4.1.3 on 2024-05-22 13:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.CharField(choices=[('None', 'None'), ('General', 'General'), ('Lifetime', 'Lifetime'), ('System', 'System')], default='None', max_length=16),
        ),
        migrations.CreateModel(
            name='MembershipClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('General', 'General'), ('Lifetime', 'Lifetime')], max_length=16)),
                ('amount_paid', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_of_registration', models.DateTimeField()),
                ('proof_of_registration', models.URLField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
