# Generated by Django 4.1.3 on 2024-08-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('None', 'None'), ('GS', 'General Secretary'), ('President', 'President'), ('EM', 'Executive Member'), ('VP', 'Vice President')], default='None', max_length=25),
        ),
    ]
