# Generated by Django 4.1.3 on 2024-01-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventannouncement',
            options={'ordering': ['-created_at']},
        ),
    ]
