# Generated by Django 4.1.3 on 2023-05-04 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmail',
            name='is_mail_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 4, 11, 45, 17, 388929, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermail',
            name='is_mail_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
