# Generated by Django 4.1.3 on 2023-05-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_commonmail_is_mail_private_usermail_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_mail_private', models.BooleanField(default=True)),
                ('recipients', models.ManyToManyField(related_name='received_common_mails', to='mailing.commonemailaddress')),
            ],
        ),
        migrations.DeleteModel(
            name='CommonMail',
        ),
    ]
