# Generated by Django 4.1.3 on 2023-05-05 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0003_systemmail_delete_commonmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmail',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_common_mails', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_user_mails', to=settings.AUTH_USER_MODEL),
        ),
    ]
