# Generated by Django 4.1.3 on 2024-01-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_systemmail_sender_alter_usermail_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermail',
            options={'ordering': ['-created_at']},
        ),
    ]
