version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - backend

    # Add environment variables for email configuration
    environment:
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=smtp.gmail.com # Replace with your SMTP server
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=alumniassociationcseduaa@gmail.com # Replace with your email
      - EMAIL_HOST_PASSWORD=qizmzjbmfirpanpo # Replace with your email password
      - DEFAULT_FROM_EMAIL=alumniassociationcseduaa@gmail.com # Default email address for notifications

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
