# Generated by Django 4.1.3 on 2024-08-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslpayment',
            name='reference',
            field=models.CharField(default='DEFAULT_REF', max_length=20),
        ),
    ]
