# Generated by Django 4.1.3 on 2024-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0002_sslpayment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
