# Generated by Django 4.1.3 on 2024-08-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0003_alter_sslpayment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslpayment',
            name='cus_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
