# Generated by Django 4.1.3 on 2024-08-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0004_sslpayment_cus_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslpayment',
            name='cus_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sslpayment',
            name='cus_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
