# Generated by Django 4.1.3 on 2024-11-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0005_sslpayment_cus_city_sslpayment_cus_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslpayment',
            name='membershipId',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sslpayment',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
