# Generated by Django 4.1.3 on 2024-11-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0006_sslpayment_membershipid_sslpayment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslpayment',
            name='membershipId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
